maddpg_agent_config_default = {
    "agent_name": "maddpg-plain",
    "state_size": 24,
    "action_size": 2,
    "num_agents": 2,
    "random_seed": 0,
    "gamma": 0.99,
    "batch_size": 128,
    "lr_actor": 2e-4,
    "lr_critic": 2e-4,
    "weight_decay": 0.0,
    "tau": 1e-2,
    "noise_decay": 1.0,
    "update_every": 2,
    "buffer_size": 1e5,
    "combined_reply_buffer": False,
    "use_per": False,
}

maddpg_agent_config_per = {
    "agent_name": "maddpg-per",
    "state_size": 24,
    "action_size": 2,
    "num_agents": 2,
    "random_seed": 0,
    "gamma": 0.99,
    "batch_size": 128,
    "lr_actor": 2e-4,
    "lr_critic": 2e-4,
    "weight_decay": 0.0,
    "tau": 1e-2,
    "noise_decay": 1.0,
    "update_every": 2,
    "buffer_size": 1e5,
    "combined_reply_buffer": False,
    "use_per": True,
}
