agent_config_default = {
    "agent_name": "ddpg-plain",
    "state_size": 33,
    "action_size": 4,
    "critic_state_hidden_layers": [400],
    "critic_action_hidden_layers": [400, 300],
    "critic_hidden_activation": "ReLU",
    "critic_output_activation": "Sigmoid",
    "critic_use_batchnorm": False,
    "actor_hidden_layers": [400, 300],
    "actor_hidden_activation": "ReLU",
    "actor_output_activation": "Tanh",
    "actor_use_batchnorm": False,
    "w_init": 3e-3,
    "seed": 0,
    "gamma": 0.99,
    "tau": 0.001,
    "batch_size": 128,
    "lr_actor": 0.001,
    "lr_critic": 0.001,
    "clip_gradient_critic": True,
    "clip_gradient_norm": 1.0,
    "clip_gradient_actor": False,
    "noise_decay": 0.999,
    "update_every": 2,
    "buffer_size": 1e5,
    "combined_reply_buffer": False,
}
